// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webhoa.Entities;

#nullable disable

namespace webhoa.Migrations
{
    [DbContext(typeof(WebbanhoaContext))]
    [Migration("20231212162055_Flower")]
    partial class Flower
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webhoa.Entities.DonHang", b =>
                {
                    b.Property<int>("MaDh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDh"));

                    b.Property<int?>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<int?>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("MaDh");

                    b.HasIndex("MaKh");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("webhoa.Entities.GioHang", b =>
                {
                    b.Property<int>("MaGh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaGH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGh"));

                    b.Property<int?>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<int?>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("MaGh");

                    b.HasIndex("MaKh");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("webhoa.Entities.Hoa", b =>
                {
                    b.Property<int>("MaSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSp"));

                    b.Property<decimal?>("Gia")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Hinhanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("Mausac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenSP");

                    b.Property<string>("Xuatxu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSp");

                    b.HasIndex("MaLoai");

                    b.ToTable("Hoa", (string)null);
                });

            modelBuilder.Entity("webhoa.Entities.KhachHang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKh"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sdt")
                        .HasColumnType("int")
                        .HasColumnName("SDT");

                    b.Property<string>("TenKh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenKH");

                    b.Property<string>("TenTk")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenTK");

                    b.HasKey("MaKh");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("webhoa.Entities.LoaiHoa", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("TenLoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiHoa", (string)null);
                });

            modelBuilder.Entity("webhoa.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("MaTk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTk"));

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTk")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenTK");

                    b.HasKey("MaTk");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("webhoa.Entities.DonHang", b =>
                {
                    b.HasOne("webhoa.Entities.KhachHang", "MaKhNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK_DonHang_KhachHang");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("webhoa.Entities.GioHang", b =>
                {
                    b.HasOne("webhoa.Entities.KhachHang", "MaKhNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK_GioHang_KhachHang");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("webhoa.Entities.Hoa", b =>
                {
                    b.HasOne("webhoa.Entities.LoaiHoa", "MaLoaiNavigation")
                        .WithMany("Hoas")
                        .HasForeignKey("MaLoai")
                        .HasConstraintName("FK_Hoa_LoaiHoa");

                    b.Navigation("MaLoaiNavigation");
                });

            modelBuilder.Entity("webhoa.Entities.KhachHang", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("webhoa.Entities.LoaiHoa", b =>
                {
                    b.Navigation("Hoas");
                });
#pragma warning restore 612, 618
        }
    }
}
